import { StringAdapter } from "casbin";

export const adapter = new StringAdapter(`
p, admin, user, (list)| (create)
p, admin, user/*, (show)|(edit)|(delete)
p, anonymous, user, (list)
p, anonymous, user/*, (show)
p, admin, district, (list)| (create)
p, admin, district/*, (show)|(edit)|(delete)
p, anonymous, district, (list) | (create)
p, anonymous, district/*, (show)| (list)
p, admin, graduation, (list)| (create)
p, admin, graduation/*, (show)|(edit)|(delete)
p, anonymous, graduation, (list) | (create)
p, anonymous, graduation/*, (show)| (list)
p, admin, profile, (list)| (create)
p, admin, profile/*, (show)|(edit)|(delete)
p, anonymous, profile, (list) | (create)
p, anonymous, profile/*, (show)| (list)
p, admin, education, (list)| (create)
p, admin, education/*, (show)|(edit)|(delete)
p, anonymous, education, (list) | (create)
p, anonymous, education/*, (show)| (list)
p, admin, document, (list)| (create)
p, admin, document/*, (show)|(edit)|(delete)
p, anonymous, document, (list) | (create)
p, anonymous, document/*, (show)| (list)
p, admin, physical_profile, (list)| (create)
p, admin, physical_profile/*, (show)|(edit)|(delete)
p, anonymous, physical_profile, (list) | (create)
p, anonymous, physical_profile/*, (show)| (list)
p, admin, branch, (list)| (create)
p, admin, branch/*, (show)|(edit)|(delete)
p, anonymous, branch, (list) | (create)
p, anonymous, branch/*, (show)| (list)
p, admin, sector, (list)| (create)
p, admin, sector/*, (show)|(edit)|(delete)
p, anonymous, sector, (list) | (create)
p, anonymous, sector/*, (show)| (list)
p, admin, position, (list)| (create)
p, admin, position/*, (show)|(edit)|(delete)
p, anonymous, position, (list) | (create)
p, anonymous, position/*, (show)| (list)
p, admin, employee, (list)| (create)
p, admin, employee/*, (show)|(edit)|(delete)
p, anonymous, employee, (list) | (create)
p, anonymous, employee/*, (show)| (list)
p, admin, application, (list)| (create)
p, admin, application/*, (show)|(edit)|(delete)
p, anonymous, application, (list) | (create)
p, anonymous, application/*, (show)| (list)
p, admin, work_experience, (list)| (create)
p, admin, work_experience/*, (show)|(edit)|(delete)
p, anonymous, work_experience, (list) | (create)
p, anonymous, work_experience/*, (show)| (list)
`);